ALTER TABLE products ADD COLUMN rating VARCHAR(50) DEFAULT NULL;
ALTER TABLE products ADD COLUMN badge VARCHAR(50) DEFAULT NULL;
ALTER TABLE products ADD COLUMN isBargainable BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN sellerName VARCHAR(191) DEFAULT NULL;
